openapi: 3.0.0
info:
  title: This is a sample application to demonstrate login logout functionality
  description: This example is created using Node.js, Express, JWT, TypeScript.
  version: 1.0.0

servers:
  - url: http://localhost:4000
    description: Local development server

paths:
  /login:
    post:
      summary: User Login
      description: Authenticates the user and returns a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: secret123
      responses:
        200:
          description: Successfully authenticated
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  body:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
        401:
          description: Unauthorized - Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  error:
                    type: string
                    example: "Invalid email or password"

  /logout:
    post:
      summary: User Logout
      description: Logs the user out by invalidating the JWT token (handled client-side).
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successfully logged out
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Successfully logged out"
        401:
          description: Unauthorized - Invalid or missing token
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 401
                  error:
                    type: string
                    example: "Unauthorized"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
